import pandas as pd

configfile: "../config/config-glicid-scratch.yml"

# ---------------------------------------------------------------------------
# Read TSV of samples - patterns to test 
# ---------------------------------------------------------------------------
samples_df = pd.read_csv(config["patternsPerSample"], sep="\t", dtype={"sample": str, "nb_patterns": int})

# Dictionarie  {sample : nb_patterns} 
all_sample_patterns = dict(zip(samples_df["sample"], samples_df["nb_patterns"]))

SAMPLES = config["samples"] #samples to test


SAMPLE_PATTERNS = {s: all_sample_patterns[s] for s in SAMPLES} #keep only samples in the tsv files

reportqmd = config["reportqmd"]

# ---------------------------------------------------------------------------
# Function to generate outputs files for rule all()
# ---------------------------------------------------------------------------
def all_outputs():
    outputs = []
    for sample, npatterns in SAMPLE_PATTERNS.items(): #iterable object

        s = sample
        n = npatterns
        base = config["cogapsOutDir"] + f"/{s}/cogaps/patterns_{n}"
        prefix = f"{s}.npatterns-{n}"

        # Markers Excel and DotPlot
        outputs.append(f"{base}/markers/{prefix}.markers.xlsx")
        outputs.append(f"{base}/markers/{prefix}.dotplot.png")

        # Contributions
        outputs.append(f"{base}/contributions/{prefix}.contributions_cells.txt")
        outputs.append(f"{base}/contributions/{prefix}.contributions_genes.txt")

        # Pattern specificity PDF
        outputs.append(f"{base}/specificity/{prefix}.plot_patterns.png")
        outputs.append(f"{base}/specificity/{prefix}.plot_subclones.png")

        # Hallmarks enrichment & overrepresentation CSVs
        outputs.append(f"{base}/hallmarks/get_function/enrichment/{prefix}.hallmarks_enrichment.csv")
        outputs.append(f"{base}/hallmarks/get_function/overrep/{prefix}.hallmarks_overrepresentation.csv")
        outputs.append(f"{base}/hallmarks/manually/enrichment/{prefix}.hallmarks_enrichment.csv")
        outputs.append(f"{base}/hallmarks/manually/overrep/{prefix}.hallmarks_overrepresentation.csv")

        # Hallmarks unique PDFs
        outputs.append(f"{base}/hallmarks/get_function/enrichment/{prefix}.hallmarks_enrichment_unique.png")
        outputs.append(f"{base}/hallmarks/get_function/overrep/{prefix}.hallmarks_overrepresentation_unique.png")

        # Hallmarks PDFs
        outputs.append(f"{base}/hallmarks/get_function/enrichment/{prefix}.hallmarks_enrichment.pdf")
        outputs.append(f"{base}/hallmarks/get_function/overrep/{prefix}.hallmarks_overrepresentation.pdf")

        # Statistics
        outputs.append(f"{base}/statistics/{prefix}.kw_results.csv")
        outputs.append(f"{base}/statistics/{prefix}.pairwise_results.csv")

        # Heatmaps
        outputs.append(f"{base}/hallmarks/get_function/enrichment/{prefix}.hallmarks_enrichment_heatmap.png")
        outputs.append(f"{base}/hallmarks/get_function/overrep/{prefix}.hallmarks_overrepresentation_heatmap.png")
        outputs.append(f"{base}/hallmarks/manually/enrichment/{prefix}.hallmarks_enrichment_heatmap.png")
        outputs.append(f"{base}/hallmarks/manually/overrep/{prefix}.hallmarks_overrepresentation_heatmap.png")

        # UMAP dominant
        for dataset in ["scrnaseq", "scatacseq", "multimodal", "nmf"]:
            outputs.append(f"{base}/umap/dominant/{prefix}.UMAP_dominant_{dataset}.png")

        # UMAP nb_cells
        outputs.append(f"{base}/umap/dominant/infos/{prefix}.nb_cells_bysubclones.png")
        outputs.append(f"{base}/umap/dominant/infos/{prefix}.nb_cells_bypatterns.png")

        # UMAP coords NMF
        outputs.append(f"{base}/umap/coo/{prefix}.nmf.umap-coords.txt")

        # UMAP weight
        for dataset in ["scrnaseq", "scatacseq", "multimodal", "nmf"]:
            outputs.append(f"{base}/umap/weight/{prefix}.UMAP_weight_{dataset}.png")

#        outputs.append(config["cogapsOutDir"] + f"/{s}/cogaps/clustree/clustree_table.tsv")
#        outputs.append(config["cogapsOutDir"] + f"/{s}/cogaps/clustree/clustree.pdf")

        # Recap global (par sample)
        outputs.append(config["cogapsOutDir"] + f"/{s}/cogaps/patterns_recap_global.csv")

        #Quarto render HTML
        outputs.append(f"{base}/report/{prefix}.report.html")

    # Maya (par sample uniquement, pas de npatterns)
    for sample in SAMPLES:
        maya_base = config["mayaOutDir"] + f"/{sample}/maya"
        outputs.append(f"{maya_base}/heatmap_cluster_cols_rows.png")
        outputs.append(f"{maya_base}/heatmap_cluster_rows_only.png")
        outputs.append(f"{maya_base}/umap_clone_annotation.png")
        outputs.append(f"{maya_base}/ALL_modules_top_contrib_genes.pdf")
        outputs.append(f"{maya_base}/ALL_modules_specificity.pdf")

    # Dédoublonnage (clustree / recap apparaissent une fois par sample)
    return list(dict.fromkeys(outputs))


# ---------------------------------------------------------------------------
# Rules
# ---------------------------------------------------------------------------

rule all:
    input:
        all_outputs()


rule cogaps:
    input:
        tumor_rna_seuratobj=config["dataDir"] + "/{sample}/{sample}.scrnaseq.icagen-filtered.seurat-object.Rds"
    output:
        cogaps_rds=config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/object/{sample}.npatterns-{npatterns}.cogaps-object.Rds"
    log:
        "logs/{sample}/{sample}-{npatterns}.log"
    benchmark:
        "benchmarks/{sample}/{sample}-{npatterns}.tsv"
    conda:
        "envs/cogaps.yml"
    threads: 65
    params:
        npatterns="{npatterns}",
        nIterations=config["cogapsIterations"]
    script:
        "scripts/run_cogaps.R"


rule reduce_dim_cogaps:
    input:
        contrib_tsv=config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/contributions/{sample}.npatterns-{npatterns}.contributions_cells.txt",
    output:
        tsv=config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/umap/coo/{sample}.npatterns-{npatterns}.nmf.umap-coords.txt",
    conda:
        "envs/cogaps.yml"
    threads: 1
    script:
        "scripts/reduce_dim.R"


rule pattern_markers:
    input:
        cogaps_rds=config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/object/{sample}.npatterns-{npatterns}.cogaps-object.Rds"
    output:
        excel=config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/markers/{sample}.npatterns-{npatterns}.markers.xlsx"
    conda:
        "envs/cogaps.yml"
    threads: 1
    script:
        "scripts/run_pattern_markers.R"


rule cells_contribution:
    input:
        cogaps_rds=config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/object/{sample}.npatterns-{npatterns}.cogaps-object.Rds"
    output:
        tsv=config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/contributions/{sample}.npatterns-{npatterns}.contributions_cells.txt"
    conda:
        "envs/cogaps.yml"
    threads: 1
    script:
        "scripts/cells_contribution.R"

rule genes_contribution:
    input:
        cogaps_rds=config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/object/{sample}.npatterns-{npatterns}.cogaps-object.Rds"
    output:
        tsv=config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/contributions/{sample}.npatterns-{npatterns}.contributions_genes.txt"
    conda:
        "envs/cogaps.yml"
    threads: 1
    script:
        "scripts/genes_contribution.R"

rule patterns_specificity:
    input:
        contributions_file=config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/contributions/{sample}.npatterns-{npatterns}.contributions_cells.txt",
        subclone=config["subcloneDir"] + "/{sample}/seurat-multimodal_vars30-30/clusters/clusters_vars30-30_res0.4.tsv",
    output:
        png1=config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/specificity/{sample}.npatterns-{npatterns}.plot_patterns.png",
        png2=config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/specificity/{sample}.npatterns-{npatterns}.plot_subclones.png"
    conda:
        "envs/cogaps.yml"
    threads: 1
    script:
        "scripts/patterns_specificity.R"


rule generate_hallmarks:
    input:
        cogaps_rds=config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/object/{sample}.npatterns-{npatterns}.cogaps-object.Rds"
    output:
        csv_enrich=config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/hallmarks/get_function/enrichment/{sample}.npatterns-{npatterns}.hallmarks_enrichment.csv",
        csv_overr=config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/hallmarks/get_function/overrep/{sample}.npatterns-{npatterns}.hallmarks_overrepresentation.csv",
    conda:
        "envs/cogaps.yml"
    threads: 1
    script:
        "scripts/generate_hallmarks.R"

rule generate_hallmarks_manually:
    input:
        contrib_txt=config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/contributions/{sample}.npatterns-{npatterns}.contributions_genes.txt",
    output:
        gsea_csv=config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/hallmarks/manually/enrichment/{sample}.npatterns-{npatterns}.hallmarks_enrichment.csv",
        ora_csv=config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/hallmarks/manually/overrep/{sample}.npatterns-{npatterns}.hallmarks_overrepresentation.csv",
    conda:
        "envs/cogaps.yml"
    threads: 1
    script:
        "scripts/generate_hallmarks_manually.R"

rule plot_hallmarks:
    input:
        csv_enrich=config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/hallmarks/get_function/enrichment/{sample}.npatterns-{npatterns}.hallmarks_enrichment.csv",
        csv_overr=config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/hallmarks/get_function/overrep/{sample}.npatterns-{npatterns}.hallmarks_overrepresentation.csv"
    output:
        pdf_enrich=config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/hallmarks/get_function/enrichment/{sample}.npatterns-{npatterns}.hallmarks_enrichment.pdf",
        pdf_overr=config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/hallmarks/get_function/overrep/{sample}.npatterns-{npatterns}.hallmarks_overrepresentation.pdf"
    conda:
        "envs/cogaps.yml"
    threads: 1
    script:
        "scripts/plot_hallmarks.R"


rule plot_uniq_hallmarks:
    input:
        csv_enrich=config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/hallmarks/get_function/enrichment/{sample}.npatterns-{npatterns}.hallmarks_enrichment.csv",
        csv_overr=config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/hallmarks/get_function/overrep/{sample}.npatterns-{npatterns}.hallmarks_overrepresentation.csv"
    output:
        png_enrich=config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/hallmarks/get_function/enrichment/{sample}.npatterns-{npatterns}.hallmarks_enrichment_unique.png",
        png_overr=config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/hallmarks/get_function/overrep/{sample}.npatterns-{npatterns}.hallmarks_overrepresentation_unique.png"
    conda:
        "envs/cogaps.yml"
    threads: 1
    script:
        "scripts/plot_uniq_hallmarks.R"



rule patterns_significance:
    input:
        contributions_file=config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/contributions/{sample}.npatterns-{npatterns}.contributions_cells.txt",
        subclone=config["subcloneDir"] + "/{sample}/seurat-multimodal_vars30-30/clusters/clusters_vars30-30_res0.4.tsv",
    output:
        kw_csv=config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/statistics/{sample}.npatterns-{npatterns}.kw_results.csv",
        pairwise_csv=config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/statistics/{sample}.npatterns-{npatterns}.pairwise_results.csv"
    conda:
        "envs/cogaps.yml"
    threads: 1
    script:
        "scripts/patterns_significance.R"


rule plot_markers:
    input:
        contrib = config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/contributions/{sample}.npatterns-{npatterns}.contributions_cells.txt",
        tumor_rna_seuratobj = config["dataDir"] + "/{sample}/{sample}.scrnaseq.icagen-filtered.seurat-object.Rds",
        markers_excel = config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/markers/{sample}.npatterns-{npatterns}.markers.xlsx"
    output:
        png=config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/markers/{sample}.npatterns-{npatterns}.dotplot.png"
    conda:
        "envs/cogaps.yml" 
    threads: 1
    script:
        "scripts/plot_markers.R"


rule plot_hallmarks_heatmap:
    input:
        csv_enrich=config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/hallmarks/get_function/enrichment/{sample}.npatterns-{npatterns}.hallmarks_enrichment.csv",
        csv_overr=config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/hallmarks/get_function/overrep/{sample}.npatterns-{npatterns}.hallmarks_overrepresentation.csv"
    output:
        png_heatmap_enrich=config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/hallmarks/get_function/enrichment/{sample}.npatterns-{npatterns}.hallmarks_enrichment_heatmap.png",
        png_heatmap_overr=config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/hallmarks/get_function/overrep/{sample}.npatterns-{npatterns}.hallmarks_overrepresentation_heatmap.png"
    conda:
        "envs/cogaps.yml"
    threads: 1
    script:
        "scripts/plot_hallmarks_heatmap.R"


rule plot_hallmarks_heatmap_manually:
    input:
        csv_enrich =  config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/hallmarks/manually/enrichment/{sample}.npatterns-{npatterns}.hallmarks_enrichment.csv",
        csv_overr =  config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/hallmarks/manually/overrep/{sample}.npatterns-{npatterns}.hallmarks_overrepresentation.csv"
    output:
        png_heatmap_enrich = config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/hallmarks/manually/enrichment/{sample}.npatterns-{npatterns}.hallmarks_enrichment_heatmap.png",
        png_heatmap_overr = config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/hallmarks/manually/overrep/{sample}.npatterns-{npatterns}.hallmarks_overrepresentation_heatmap.png"
    conda:
        "envs/cogaps.yml"
    threads: 1
    script:
        "scripts/plot_hallmarks_heatmap_manually.R"


rule umap_dominant:
    input:
        contributions=config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/contributions/{sample}.npatterns-{npatterns}.contributions_cells.txt",
        umap=lambda wildcards: (
            config["cooDir_combined"] + f"/{wildcards.sample}/{wildcards.sample}.scrnaseq.icagen-filtered.normalized-sctransform-v2.umap-coords.tsv"
            if wildcards.dataset == "scrnaseq"
            else config["cooDir_combined"] + f"/{wildcards.sample}/{wildcards.sample}.scatacseq.icagen-filtered.umap-coords.tsv"
            if wildcards.dataset == "scatacseq"
            else config["cooDir_multimodal"] + f"/{wildcards.sample}/seurat-multimodal/dims8-8/umaps/coords-multimodal-umap_dims8-8.tsv"
            if wildcards.dataset == "multimodal"
            else config["cogapsOutDir"] + f"/{wildcards.sample}/cogaps/patterns_{wildcards.npatterns}/umap/coo/{wildcards.sample}.npatterns-{wildcards.npatterns}.nmf.umap-coords.txt"
        )
    output:
        png=config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/umap/dominant/{sample}.npatterns-{npatterns}.UMAP_dominant_{dataset}.png"
    params:
        dataset="{dataset}"
    wildcard_constraints:
        dataset="scrnaseq|scatacseq|multimodal|nmf"
    conda:
        "envs/cogaps.yml"
    script:
        "scripts/plot_umap_dominant.R"


rule umap_weight:
    input:
        contributions=config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/contributions/{sample}.npatterns-{npatterns}.contributions_cells.txt",
        umap=lambda wildcards: (
            config["cooDir_combined"] + f"/{wildcards.sample}/{wildcards.sample}.scrnaseq.icagen-filtered.normalized-sctransform-v2.umap-coords.tsv"
            if wildcards.dataset == "scrnaseq"
            else config["cooDir_combined"] + f"/{wildcards.sample}/{wildcards.sample}.scatacseq.icagen-filtered.umap-coords.tsv"
            if wildcards.dataset == "scatacseq"
            else config["cooDir_multimodal"] + f"/{wildcards.sample}/seurat-multimodal/dims8-8/umaps/coords-multimodal-umap_dims8-8.tsv"
            if wildcards.dataset == "multimodal"
            else config["cogapsOutDir"] + f"/{wildcards.sample}/cogaps/patterns_{wildcards.npatterns}/umap/coo/{wildcards.sample}.npatterns-{wildcards.npatterns}.nmf.umap-coords.txt"
        )
    output:
        png=config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/umap/weight/{sample}.npatterns-{npatterns}.UMAP_weight_{dataset}.png"
    params:
        dataset="{dataset}"
    wildcard_constraints:
        dataset="scrnaseq|scatacseq|multimodal|nmf"
    conda:
        "envs/cogaps.yml"
    script:
        "scripts/plot_umap_weight.R"


rule nb_cells:
    input:
        contrib=config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/contributions/{sample}.npatterns-{npatterns}.contributions_cells.txt",
        subclones=config["subcloneDir"] + "/{sample}/seurat-multimodal_vars30-30/clusters/clusters_vars30-30_res0.4.tsv",
    output:
        png1=config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/umap/dominant/infos/{sample}.npatterns-{npatterns}.nb_cells_bysubclones.png",
        png2=config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/umap/dominant/infos/{sample}.npatterns-{npatterns}.nb_cells_bypatterns.png"
    conda:
        "envs/cogaps.yml"
    threads: 1
    script:
        "scripts/plot_nb_cells.R"


rule pathway_activity_maya:
    input:
        seurat=config["dataDir"] + "/{sample}/{sample}.scrnaseq.icagen-filtered.seurat-object.Rds",
        subclone=config["subcloneDir"] + "/{sample}/seurat-multimodal_vars30-30/clusters/clusters_vars30-30_res0.4.tsv"
    output:
        heatmap1=config["mayaOutDir"] + "/{sample}/maya/heatmap_cluster_cols_rows.png",
        heatmap2=config["mayaOutDir"] + "/{sample}/maya/heatmap_cluster_rows_only.png",
        umap=config["mayaOutDir"] + "/{sample}/maya/umap_clone_annotation.png",
        top_genes=config["mayaOutDir"] + "/{sample}/maya/ALL_modules_top_contrib_genes.pdf",
        specificity=config["mayaOutDir"] + "/{sample}/maya/ALL_modules_specificity.pdf"
    conda:
        "envs/maya.yml"
    threads: 1
    script:
        "scripts/pathway_activity_maya.R"


rule dominant_patterns_summary:
    input:
        lambda wildcards: expand(
            config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/contributions/{sample}.npatterns-{npatterns}.contributions_cells.txt",
            sample=wildcards.sample,
            npatterns=SAMPLE_PATTERNS[wildcards.sample]
        )
    output:
        tsv=config["cogapsOutDir"] + "/{sample}/cogaps/clustree/clustree_table.tsv"
    conda:
        "envs/cogaps.yml"
    script:
        "scripts/dominant_patterns_summary.R"


rule plot_clustree:
    input:
        table=config["cogapsOutDir"] + "/{sample}/cogaps/clustree/clustree_table.tsv"
    output:
        pdf=config["cogapsOutDir"] + "/{sample}/cogaps/clustree/clustree.pdf"
    conda:
        "envs/cogaps.yml"
    script:
        "scripts/plot_clustree.R"


rule recap_patterns_global:
    input:
        cogaps_files=lambda wildcards: [
            config["cogapsOutDir"] + f"/{wildcards.sample}/cogaps/patterns_{SAMPLE_PATTERNS[wildcards.sample]}/object/{wildcards.sample}.npatterns-{SAMPLE_PATTERNS[wildcards.sample]}.cogaps-object.Rds"
        ]
    output:
        csv=config["cogapsOutDir"] + "/{sample}/cogaps/patterns_recap_global.csv"
    conda:
        "envs/cogaps.yml"
    threads: 1
    script:
        "scripts/recap_patterns_global.R"

    
rule render_report:
    input:
        qmd=reportqmd,
        contrib_cells=config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/contributions/{sample}.npatterns-{npatterns}.contributions_cells.txt",
        contrib_genes=config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/contributions/{sample}.npatterns-{npatterns}.contributions_genes.txt",
        markers_excel=config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/markers/{sample}.npatterns-{npatterns}.markers.xlsx",
        dotplot=config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/markers/{sample}.npatterns-{npatterns}.dotplot.png",
        enrich_csv=config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/hallmarks/get_function/enrichment/{sample}.npatterns-{npatterns}.hallmarks_enrichment.csv",
        overr_csv=config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/hallmarks/get_function/overrep/{sample}.npatterns-{npatterns}.hallmarks_overrepresentation.csv",
        kw_csv=config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/statistics/{sample}.npatterns-{npatterns}.kw_results.csv",
        pairwise_csv=config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/statistics/{sample}.npatterns-{npatterns}.pairwise_results.csv",
        png_specificity_patterns=config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/specificity/{sample}.npatterns-{npatterns}.plot_patterns.png",
        png_specificity_subclones=config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/specificity/{sample}.npatterns-{npatterns}.plot_subclones.png",
        png_enrich_unique=config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/hallmarks/get_function/enrichment/{sample}.npatterns-{npatterns}.hallmarks_enrichment_unique.png",
        png_overr_unique=config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/hallmarks/get_function/overrep/{sample}.npatterns-{npatterns}.hallmarks_overrepresentation_unique.png",
        png_enrich_heatmap=config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/hallmarks/get_function/enrichment/{sample}.npatterns-{npatterns}.hallmarks_enrichment_heatmap.png",
        png_overr_heatmap=config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/hallmarks/get_function/overrep/{sample}.npatterns-{npatterns}.hallmarks_overrepresentation_heatmap.png",
        png_enrich_heatmap_manually=config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/hallmarks/manually/enrichment/{sample}.npatterns-{npatterns}.hallmarks_enrichment_heatmap.png",
        png_overr_heatmap_manually=config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/hallmarks/manually/overrep/{sample}.npatterns-{npatterns}.hallmarks_overrepresentation_heatmap.png",
        umap_scrnaseq=config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/umap/dominant/{sample}.npatterns-{npatterns}.UMAP_dominant_scrnaseq.png",
        umap_scatacseq=config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/umap/dominant/{sample}.npatterns-{npatterns}.UMAP_dominant_scatacseq.png",
        umap_multimodal=config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/umap/dominant/{sample}.npatterns-{npatterns}.UMAP_dominant_multimodal.png",
        umap_nmf=config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/umap/dominant/{sample}.npatterns-{npatterns}.UMAP_dominant_nmf.png",
        umap_nb_cells_bysubclones=config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/umap/dominant/infos/{sample}.npatterns-{npatterns}.nb_cells_bysubclones.png",
        umap_nb_cells_bypatterns=config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/umap/dominant/infos/{sample}.npatterns-{npatterns}.nb_cells_bypatterns.png",
        weight_scrnaseq=config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/umap/weight/{sample}.npatterns-{npatterns}.UMAP_weight_scrnaseq.png",
        weight_scatacseq=config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/umap/weight/{sample}.npatterns-{npatterns}.UMAP_weight_scatacseq.png",
        weight_multimodal=config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/umap/weight/{sample}.npatterns-{npatterns}.UMAP_weight_multimodal.png",
        weight_nmf=config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/umap/weight/{sample}.npatterns-{npatterns}.UMAP_weight_nmf.png",
    output:
        html=config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/report/{sample}.npatterns-{npatterns}.report.html"
    params:
        outdir=config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/report",
        sample="{sample}",
        npatterns="{npatterns}"
    log:
        "logs/{sample}/{sample}-{npatterns}.render_report.log"
    conda:
        "envs/quarto.yml"
    threads: 1
    shell:
        """
        LOGFILE=$(realpath {log})
        mkdir -p "{params.outdir}"
        cp {input.qmd} "{params.outdir}/report_cogaps.qmd"
        cd "{params.outdir}"
        quarto render report_cogaps.qmd \
            --output {params.sample}.npatterns-{params.npatterns}.report.html \
            -P sample:{params.sample} \
            -P npatterns:{params.npatterns} \
            -P outdir:"{params.outdir}" \
            -P contrib_cells:{input.contrib_cells} \
            -P contrib_genes:{input.contrib_genes} \
            -P markers_excel:{input.markers_excel} \
            -P dotplot:{input.dotplot} \
            -P enrich_csv:{input.enrich_csv} \
            -P overr_csv:{input.overr_csv} \
            -P kw_csv:{input.kw_csv} \
            -P pairwise_csv:{input.pairwise_csv} \
            -P png_specificity_patterns:{input.png_specificity_patterns} \
            -P png_specificity_subclones:{input.png_specificity_subclones} \
            -P png_enrich_unique:{input.png_enrich_unique} \
            -P png_overr_unique:{input.png_overr_unique} \
            -P png_enrich_heatmap:{input.png_enrich_heatmap} \
            -P png_overr_heatmap:{input.png_overr_heatmap} \
            -P png_enrich_heatmap_manually:{input.png_enrich_heatmap_manually} \
            -P png_overr_heatmap_manually:{input.png_overr_heatmap_manually} \
            -P umap_scrnaseq:{input.umap_scrnaseq} \
            -P umap_scatacseq:{input.umap_scatacseq} \
            -P umap_multimodal:{input.umap_multimodal} \
            -P umap_nmf:{input.umap_nmf} \
            -P umap_nb_cells_bysubclones:{input.umap_nb_cells_bysubclones} \
            -P umap_nb_cells_bypatterns:{input.umap_nb_cells_bypatterns} \
            -P weight_scrnaseq:{input.weight_scrnaseq} \
            -P weight_scatacseq:{input.weight_scatacseq} \
            -P weight_multimodal:{input.weight_multimodal} \
            -P weight_nmf:{input.weight_nmf} \
        > "$LOGFILE" 2>&1
        rm -f "{params.outdir}/report_cogaps.qmd"
        """